# https://docs.docker.com/compose/compose-file/#environment
version: '3.8'
services:
  sut:
    build:
      context: .

  runner:
    image: quay.io/cybozu/ubuntu:18.04
    volumes:
      - ./test:/work:ro
    working_dir: /work
    command: ./test.sh
